FROM phusion/baseimage:0.10.1

ENV DEBIAN_FRONTEND noninteractive

# php packages
RUN add-apt-repository ppa:ondrej/php && apt update && apt-get install -y \
    pkg-config \
    php7.2-cli php7.2-fpm \
    php7.2-pgsql php7.2-sqlite3 \
    php7.2-xdebug \
    php7.2-gd \
    php7.2-curl \
    php7.2-intl \
    php7.2-dev \
    php7.2-mbstring \
    php7.2-bcmath \
    php7.2-zip

# other packages
RUN apt-get install -y sudo git

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/bin

# clean
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    mkdir /home/www-data && \
    chsh -s /bin/bash www-data

ADD php.ini /etc/php/7.2/cli/conf.d/php.ini